/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.login;

/**
 *
 * @author dquin
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        bg = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        Lb_title = new javax.swing.JLabel();
        city = new javax.swing.JLabel();
        nombre_colegio = new javax.swing.JLabel();
        iniciar_secion = new javax.swing.JLabel();
        sep_contraseña = new javax.swing.JSeparator();
        Lb_contraseña = new javax.swing.JLabel();
        Lb_usuario = new javax.swing.JLabel();
        Tf_usuario = new javax.swing.JTextField();
        sep_usuario = new javax.swing.JSeparator();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setForeground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/logo.png"))); // NOI18N
        bg.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, 270, -1));

        Lb_title.setBackground(new java.awt.Color(255, 255, 255));
        Lb_title.setForeground(new java.awt.Color(255, 255, 255));
        Lb_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lb_title.setText("TITLE");
        bg.add(Lb_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 230, 70, -1));

        city.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/city.png"))); // NOI18N
        bg.add(city, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 270, 400));

        nombre_colegio.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        nombre_colegio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/favicon.png"))); // NOI18N
        nombre_colegio.setText("Colegio \"Melchor Pinto Parada 2\"");
        bg.add(nombre_colegio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 240, -1));

        iniciar_secion.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        iniciar_secion.setText("INICIAR SECION");
        bg.add(iniciar_secion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));
        bg.add(sep_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 330, 20));

        Lb_contraseña.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Lb_contraseña.setText("CONTRASEÑA");
        bg.add(Lb_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        Lb_usuario.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Lb_usuario.setText("USUARIO");
        bg.add(Lb_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        Tf_usuario.setForeground(new java.awt.Color(204, 204, 204));
        Tf_usuario.setText("INGRESE UN USUARIO");
        Tf_usuario.setBorder(null);
        bg.add(Tf_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 330, -1));
        bg.add(sep_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 330, 20));

        jPasswordField1.setForeground(new java.awt.Color(204, 204, 204));
        jPasswordField1.setText("jPasswordField1");
        jPasswordField1.setBorder(null);
        bg.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 330, 30));

        jPanel1.setBackground(new java.awt.Color(0, 134, 190));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("INGRESAR");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 200, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lb_contraseña;
    private javax.swing.JLabel Lb_title;
    private javax.swing.JLabel Lb_usuario;
    private javax.swing.JTextField Tf_usuario;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel city;
    private javax.swing.JLabel iniciar_secion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel nombre_colegio;
    private javax.swing.JSeparator sep_contraseña;
    private javax.swing.JSeparator sep_usuario;
    // End of variables declaration//GEN-END:variables
}
